---
title: "Plot analysis"
author: "Kshitij-Bashir"
date: "11/26/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
library(tidyverse)
library(base)
library(gridExtra)
```

```{r}
# comparing total co2 producation between countries across time
climate_data <- read.csv("~/Mscs 264 F19/Project/Bashir_Kshitij Project/climate_data.csv")
Forest <- read.csv("~/Mscs 264 F19/Project/Bashir_Kshitij Project/Forest.csv")
Glacier <- read_csv("~/Mscs 264 F19/Project/Bashir_Kshitij Project/glaciers_csv.csv")
co2_fossile_nation<-read_csv("~/Mscs 264 F19/Project/Bashir_Kshitij Project/fossil-fuel-co2-emissions-by-nation_csv.csv")
methane<-read_csv("~/Mscs 264 F19/Project/Bashir_Kshitij Project/data_csv.csv")
```

```{r}
# converting datasets into tibble
climate_data<- as.tibble(climate_data)
Forest <- as.tibble(Forest)
Glacier<-as.tibble(Glacier)
co2_fossile_nation<-as.tibble(co2_fossile_nation)
# subseting methan into region and country
methane.region<- methane[1:1978,]
methane.nation<-methane[1979:nrow(methane),]
# renaming 
Glacier<-Glacier%>%
rename(Mean_cumulative_mass_balance=`Mean cumulative mass balance`)
Glacier$Year = as.numeric(Glacier$Year)
climate_data$Year=as.Date(climate_data$Year)
# co2_fossile_nation$Year=as.Date(co2_fossile_nation$Year)
# plots
solid<-ggplot(data = climate_data, aes(x= (Year), y = CO2_solid.fuel))+
  geom_point()
land<-ggplot(data = climate_data, aes(x= (Year), y = land.temp))+
  geom_point()
Glacier<-ggplot(data =Glacier, aes(x=Year, y = Mean_cumulative_mass_balance))+
  geom_point()
sealevel<-ggplot(data = climate_data, aes(x= Year, y = CSIRO.Adjusted.Sea.Level))+
  geom_point()
plots.climate <- grid.arrange(solid, land, Glacier, sealevel,
                                   ncol=2)
# Creating difference column for 1990-2016 forest
Forest.diff<-Forest_Area%>%
  mutate(For.diff = `1990`-`2016`)%>%
  arrange(desc(For.diff)) 
# Plots for top 5 countries with higest difference in forest percentage betn 1990-2016
Forest%>%
  filter(Country.Code=='HND'|Country.Code=='PRK'|Country.Code=='ZWE'|
           Country.Code=='KHM'|Country.Code=='TLS')%>%
ggplot( aes(x= Country.Name, y = Forest.Area ,color = Country.Code))+
  geom_point()+
  geom_smooth(method='lm')

# scatter plot for average forest area across world vs year
Forest%>%
  group_by(Country.Name)%>%
  summarise(For.Area = mean(Forest.Area, na.rm=TRUE))%>%
  ggplot(aes(y = For.Area, x = Country.Name))+
  geom_point()

# histograms for total CO2 production
climate_data%>%
  ggplot(aes(x= Total_CO2))+
  geom_histogram(binwidth = 300)

climate_data%>%
  ggplot(aes(x= Total_CO2))+
  geom_histogram(binwidth = 300)


# CO2 emission by countries in 2014
co2_fossile_nation%>%
  filter(Year==2014)%>%
  arrange(desc(Total))%>%
  top_n(20)%>%
ggplot(aes(x = fct_reorder(Country, Total), y = Total)) +
geom_col(fill='slateblue2') + # makes bar plot where heights = values in the data set
coord_flip() +
labs(title="Top 20 countries with higest CO2 emmission 2014", x="Countries", y= "Total CO2 emmission")

# Top 5 couuntries with highest total CO2 emmisison across years
co2_fossile_nation%>%
  group_by(Country)%>%
  summarise(total_co2=mean(Total, na.rm=TRUE))%>%
  arrange(desc(total_co2))%>%
  top_n(5)

tot_co2<- co2_fossile_nation%>%
  filter(Country=='UNITED STATES OF AMERICA' |Country=='RUSSIAN FEDERATION'
         |Country=="CHINA (MAINLAND)"|Country=="JAPAN"|Country=="USSR")
ggplot(tot_co2, aes(x = Year, y = Total, color = Country))+
  geom_line()+
  labs(title="Top 5 countries with higest total CO2 emmission", y="Total CO2 emmision")
  

co2_percap<-co2_fossile_nation%>%
  filter(Year==2014)%>%
  rename(co2_percap='Per Capita')%>%
  arrange(desc(co2_percap))

ggplot(co2_percap[1:20,],aes(x = fct_reorder(Country,co2_percap ), y = co2_percap)) +
geom_col(fill='tan4') + # makes bar plot where heights = values in the data set
coord_flip() +
labs(title="Top 20 countries with higest CO2 emmission per capita in 2014", x="Countries", y = "CO2 emmisison Per capita")


# Methane
methane%>%
  filter(`Country Name`== 'World')%>%
  ggplot(aes(x=Year, y=Value))+
  geom_point()+
  labs(title="Global Methane gas emission over years", y="Methane emission")

# Methane emission by countries in 2014
methane.nation%>%
  filter(Year==2012)%>%
  arrange(desc(Value))%>%
  top_n(20)%>%
ggplot(aes(x = fct_reorder(`Country Name`, Value), y = Value)) +
geom_col(fill='slateblue2') + # makes bar plot where heights = values in the data set
coord_flip() +
labs(title="Top 20 countries with higest Methane gas emmission 2014", x="Countries", y= "Total Methane emmission")

methane.nation%>%
  filter(`Country Name`=='China'|`Country Name`=='India'|`Country Name`=='Russian Federation'|`Country Name`=='United States'|`Country Name`=='Brazil')%>% 
ggplot(aes(x = Year, y = Value, color = fct_reorder2(`Country Name`, Year, Value)))+
  geom_line()+
  labs(title="Top 5 countries with higest Methane gas emmission in 2012", x="Countries", y= "Total Methane emmission",
       colour = "Country Name")
        

# Methane emission across different region of the world throught the years
MR<-methane.region%>%
  filter(`Country Name`=='Arab World'|`Country Name`=='Caribbean small state'
         |`Country Name`=='East Asia & Pacific'|`Country Name`=='Latin America & Caribbean'|`Country Name`=="North America"|`Country Name`=="Europe & Central Asia"
         |`Country Name`=="Heavily indebted poor countries (HIPC)"
         |`Country Name`=="") 
ggplot(MR,aes(x = Year, y = Value, color =fct_reorder2(`Country Name`, Year,Value)))+
  geom_line()+
   labs(title="Methane gas emmission among different Regions around world over years", y= "Total Methane emmission", x='Region', colour='Regions')
        colour = fct_reorder2(marital, age, prop)
```
 
 